### ISSUE TITLE
Is there a read me file? 

### ISSUE THREAD

**Issue by jolespin** [jacobian1980/ecostates#1]
Is there a read me file associated with the usage of this implementation? Let's say you had a dataframe with OTUs.  How can one run the model? What are the output files?

**Comment by cascobayesian** [comment]
Hi! I used to have a README that explained some of this, but found it to be a bit inadequate and so pulled it down with the intention of putting up a better one. Of course, a not-great one is probably better than none, so that was not my most considered action. Would you prefer if I put up a README or answered your questions directly? I've been meaning to put some time into this, so this is a good opportunity!

**Comment by jolespin** [comment]
Hi thanks for getting back to me so quickly.  I want to try it out on Monday so I think a Read Me to get started would be perfect.  A few people in my lab, including me, are going to start using this starting next week.  We want to incorporate it in our pipeline!  The paper is really interesting and the tool seems incredibly useful.

**Comment by cascobayesian** [comment]
Okay... I will try to rustle one up. Since you're one of the first teams to try this outside of my collaborators, it'd be great to get some feedback about how it runs.

**Comment by cascobayesian** [comment]
I've put up a basic README that should get you through the opening steps. I'll post some additional scripts that should help you post process in the output in the next day or so. Does that help?

**Comment by jolespin** [comment]
I'm going to try it out in a few hours and let you know! Thanks so much.

**Comment by jolespin** [comment]
Hi Jack, 

We had a few questions:

(1) `the file should have a header but no row names`.  Does this mean no sample names at all (bottom right) in screenshot example ? If so, how does it know which samples cluster together based on their OTUs? Or is the method only clustering OTUs together irrespective of the samples? 
![image](https://cloud.githubusercontent.com/assets/9061708/17709753/5272f24e-639f-11e6-8013-2ae30cb13fe7.png)

(2) What is a good default `num.iter` value? For example how much should `num.iter` differ between (40 samples and 170 OTUs) vs. (150 samples 3000 OTUs)?  

(3) Once you have the markov chain for all of the iterations, how can one get: 
        (A) the OTUs that are in each cluster; 
        (B) the samples that match to a particular cluster; and 
        (C) the confidence (or some metric) that says how likely the samples matches that cluster. 

Thanks!
- Josh

**Comment by cascobayesian** [comment]
Hi,

1) The lower right corner is what you'll need. You can adjust this if you'd like to play around with the run.3.r file but if you want to use it 'straight-from-the-box' then this is what you'll need to use.

2) The number of OTUs matters less. I'd say 1000 iterations for anything less than 100 samples. However, convergence for mixture models can be an issue so consider making multiple runs to make sure. I can provide some scripts to do diagnostics on the chain, if that would help.

3) I'm writing this into the posterior chain analysis scripts, but you can get at most of (A) and (B) by knowing that a particular iteration (say 1000) can be selected by  `current[[1000]]`. The chain states (the cluster configuration) is given as `c` so `current[[1000]]$c` will show you the cluster assignments at that iteration. You can get all the samples in cluster 1 by typing 

`cluster.1 = which(current[[1000]]$c==1)`

More in a bit...

**Comment by cascobayesian** [comment]
If you have further questions, please email me at jobrien@bowdoin.edu. That should speed up the response time and allow a more tailored analysis. For the moment, I'm going to close the this issue.
